---
server:
  port: 8082

spring:
  application:
    name: zuul
  cloud:
    config:
      enabled: false

zuul:
  routes:
    test:
      path: /test/**
      stripPrefix: true
      serviceId: test
    js_service:
      path: /js_service/**
      stripPrefix: true
      serviceId: js_service
#      url: http://192.168.0.238:3000/
  ignored-services: '*'

eureka:
  instance:
    nonSecurePort: ${server.port:8082}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:192.168.0.237}:${eureka.port:8761}/eureka/
    healthcheck:
          enabled: true