---
server:
  port: 8082

spring:
  application:
    name: zuul

zuul:
  routes:
    test:
      path: /test/**
      stripPrefix: true
      serviceId: test
  ignored-services: '*'

eureka:
  instance:
    nonSecurePort: ${server.port:8082}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:192.168.1.11}:${eureka.port:8081}/eureka/